services:
  weatherservice:
    build:
      context: .
    image: steve353/weatherapi:v3.4.2
    ports:
      - 5002:5002
    volumes:
      - ./data:/app/data
      - ./keys:/app/keys
      - ./Certs:/app/Certs
      - ./.env:/app/.env:ro