services:
  weatherservice:
    build:
      context: .
    image: steve353/weatherapi:v2-1.2
    ports:
      - 5001:443
    volumes:
      - ./data:/app/data
      - ./keys:/app/keys
      - ./Certs:/app/Certs
      - ./.env:/app/.env:ro