version: "3.8"

services:
  weatherservice:
    build:
      context: .
    image: steve353/weatherapi2:1.0
    ports:
      - 5001:443
    volumes:
      - ./Data:/app/data
      - ./Keys:/app/keys
      - ./Certs:/app/Certs